Repository UIGF-org/UIGF-org.github.io, pull requests merged in 2023-09, with the labels that each got.

#32 向SRGF合作项目添加《咸鱼的崩铁助理》
  docs/en/partnership-list.md
  docs/zh/partnership-list.md
Labels: Project Registration

#33 添加SRGF合作项目 StarRailTools
  docs/.vuepress/public/partnerships/cntvc/star_rail_tools/preview.png
  docs/en/partnership-list.md
  docs/zh/partnership-list.md
Labels: Project Registration, SRGF

#34 添加UIGF合作项目 派蒙笔记本
  docs/en/partnership-list.md
  docs/zh/partnership-list.md
Labels: Project Registration, UIGF
