Repository UIGF-org/UIGF-org.github.io, pull requests merged in 2024-05, with the labels that each got.

#64 Update advices regarding Schema conformation.
  docs/.vuepress/navbar/en.ts
  docs/.vuepress/navbar/zh.ts
  docs/en/standards/srgf.md
  docs/en/standards/uiaf.md
  docs/en/standards/uigf-legacy-v2.3.md
  docs/en/standards/uigf.md
  docs/zh/standards/srgf.md
  docs/zh/standards/uiaf.md
  docs/zh/standards/uigf.md
Labels: enhancement

#65 Update partnership list, adding PizzaHelper4HSR.
  docs/en/partnership-list.md
  docs/zh/partnership-list.md
Labels: SRGF

#67 ✏️ schema没有enumDesc关键字
  docs/en/standards/uiaf.md
  docs/zh/standards/uiaf.md
Labels: UIAF
